# Site Settings
title:               "J. David Maclean"
tagline:             "Seems like the thing to do."
url:                 https://jdavidmaclean.com
paginate:            1000
baseurl:             ""
description: "J. David Maclean > A motivated solutions-driven technical thinker with a creative history and an aptitude for tutoring. Passionate about designing systems, managing projects and communicating ideas in the online, education, design, and publishing markets."

# About/contact
author:
  name:              "J. David Maclean"
  #url:               https://twitter.com/mdo
  email:             j.david.maclean@gmail.com
  
# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed
  sourcemap:        true
  
# Permalinks
permalink:           pretty

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
analytics_id:        UA-92019002-1
contentPath:         "/content"
imagesPath:          "/images"

# Build settings
#theme: minima
highlighter: none
markdown: kramdown
kramdown:
    auto_ids: false
    syntax_highlighter_opts:
        disable : true
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - _lib
